using UnityEditor;
using UnityEngine;

namespace Lineage.Editor
{
    /// <summary>
    /// Temporary script to manually open MCP For Unity window
    /// </summary>
    public static class OpenMCPWindow
    {
        [MenuItem("Tools/Debug/Open MCP Window")]
        public static void OpenWindow()
        {
            // Try to find and open the MCP window type
            try
            {
                var assembly = System.Reflection.Assembly.Load("MCPForUnity.Editor");
                if (assembly != null)
                {
                    var windowType = assembly.GetType("MCPForUnity.Editor.Windows.MCPForUnityWindow");
                    if (windowType != null)
                    {
                        EditorWindow.GetWindow(windowType, false, "MCP For Unity");
                        UnityEngine.Debug.Log("MCP Window opened successfully!");
                    }
                    else
                    {
                        UnityEngine.Debug.LogWarning("MCP Window type not found. MCP package may not be installed.");
                    }
                }
                else
                {
                    UnityEngine.Debug.LogWarning("MCPForUnity.Editor assembly not loaded. MCP package may not be installed.");
                }
            }
            catch (System.Exception ex)
            {
                UnityEngine.Debug.LogWarning($"MCP Window not available: {ex.Message}");
            }
        }

        [MenuItem("Tools/Debug/List All Assemblies")]
        public static void ListAssemblies()
        {
            foreach (var assembly in System.AppDomain.CurrentDomain.GetAssemblies())
            {
                if (assembly.FullName.Contains("MCP"))
                {
                    UnityEngine.Debug.Log($"Found assembly: {assembly.FullName}");
                }
            }
        }
    }
}
// Pseudocode generated by codewrx.ai
