using UnityEngine;
using System.Collections.Generic;

namespace Lineage.Core.Entities
{
    /// <summary>
    /// Entity type categories matching the legacy EntityType enum.
    /// </summary>
    public enum EntityCategory
    {
        Pop,
        Animal,
        NPC,
        Structure,
        Resource,
        Other
    }

    /// <summary>
    /// Definition for an entity such as a Pop, Animal, or Structure.
    /// Centralizes entity configuration for the new GameData system.
    /// </summary>
    [CreateAssetMenu(fileName = "NewEntityDef", menuName = "GameData/Entities/Entity Definition")]
    public class EntityDefinitionSO : Lineage.Core.GameDataSO
    {
        [Header("Entity Type")]
        public EntityCategory entityCategory = EntityCategory.Other;
        public GameObject prefab;

        [Header("Behavior Configuration")]
        public bool hasNeedsDecay = true;
        public bool hasAging = true;
        public bool canCraft = false;
        public bool canSocialize = false;
        public bool canGather = true;
        public bool hasTerritory = false;
        public bool canHunt = false;
        public bool canFlee = true;

        [Header("Behavior Subtypes")]
        [Tooltip("Behavior subtags like 'carnivore', 'herbivore', 'wolf', 'bandit', etc.")]
        public List<string> behaviorSubtags = new List<string>();

        [Header("Resource Configuration")]
        [Tooltip("Resource tags: 'Food', 'Water', 'Water.Clean', 'Water.Dirty', 'Gatherable', 'Crafting'")]
        public List<string> resourceTags = new List<string>();

        [Header("Base Stats")]
        public float baseHealth = 100f;
        public float baseMana = 50f;
        public float baseSpeed = 5f;
        public float baseStrength = 10f;
        public float baseAgility = 10f;
        public float baseIntelligence = 10f;
        public float baseDefense = 10f;

        [Header("Needs Decay Rates")]
        public float hungerDecayRate = 1f;
        public float thirstDecayRate = 1.5f;
        public float energyDecayRate = 0.8f;
        public float restDecayRate = 0.5f;

        [Header("Aging Configuration")]
        public float agingRate = 1f;
        public int maxAge = 100;

        [Header("Combat Configuration")]
        public float fleeHealthThreshold = 30f;
        public float aggressionLevel = 50f;

        [Header("Movement Configuration")]
        public float wanderRadius = 10f;
        public float movementSpeed = 3.5f;
        public float territoryRadius = 15f;

        [Header("Social Configuration")]
        public float socialRadius = 5f;
        public int maxSocialGroup = 6;

        [Header("Resource Gathering")]
        public float gatheringEfficiency = 1f;

        [Header("Crafting Configuration")]
        public List<string> knownRecipes = new List<string>();
    }
}
// Pseudocode generated by codewrx.ai
