using UnityEngine;
using System.Collections.Generic;

namespace Lineage.Core.Items
{
    /// <summary>
    /// Item categories for grouping and filtering.
    /// </summary>
    public enum ItemCategory
    {
        Resource,
        Material,
        Tool,
        Weapon,
        Armor,
        Consumable,
        QuestItem,
        Misc
    }

    /// <summary>
    /// Definition for an item in the game.
    /// Centralizes item data for the new GameData system.
    /// </summary>
    [CreateAssetMenu(fileName = "NewItemDef", menuName = "GameData/Items/Item Definition")]
    public class ItemDefinitionSO : Lineage.Core.GameDataSO
    {
        [Header("Item Configuration")]
        public ItemCategory category = ItemCategory.Misc;
        public int maxStackSize = 1;
        public Sprite itemIcon;

        [Header("Value & Rarity")]
        public int baseValue = 1;
        public Lineage.Database.Rarity rarity = Lineage.Database.Rarity.Common;

        [Header("Weight & Size")]
        public float weight = 1f;

        [Header("Usability")]
        public bool isConsumable = false;
        public bool isEquippable = false;
        public bool isCraftingMaterial = false;
        public bool isQuestItem = false;

        [Header("Effects (for consumables)")]
        public float healthRestore = 0f;
        public float hungerRestore = 0f;
        public float thirstRestore = 0f;
        public float energyRestore = 0f;

        [Header("Equipment Stats (for equippables)")]
        public float attackBonus = 0f;
        public float defenseBonus = 0f;
        public float speedBonus = 0f;

        [Header("Resource Tags")]
        [Tooltip("Tags like 'Food', 'Water', 'Wood', 'Stone', 'Metal', etc.")]
        public List<string> resourceTags = new List<string>();
    }
}
// Pseudocode generated by codewrx.ai
