using UnityEngine;
using System;

namespace Lineage.Tests
{
    /// <summary>
    /// Generic test action wrapper for behavior tree or action system testing.
    /// Provides a reusable structure for defining and executing test actions.
    /// </summary>
    public class TestAction : MonoBehaviour
    {
        /// <summary>
        /// Result of a test action execution.
        /// </summary>
        public enum ActionResult
        {
            Success,
            Running,
            Failure,
            NotStarted
        }

        [Header("Action Configuration")]
        [SerializeField] private string _actionName = "TestAction";
        [SerializeField] private float _duration = 1f;
        [SerializeField] private bool _shouldSucceed = true;

        [Header("Runtime State")]
        [SerializeField] private ActionResult _currentResult = ActionResult.NotStarted;
        [SerializeField] private float _elapsedTime = 0f;

        /// <summary>
        /// Event fired when the action completes.
        /// </summary>
        public event Action<ActionResult> OnActionComplete;

        /// <summary>
        /// Event fired when the action state changes.
        /// </summary>
        public event Action<ActionResult> OnStateChanged;

        /// <summary>
        /// Gets the current action result.
        /// </summary>
        public ActionResult CurrentResult => _currentResult;

        /// <summary>
        /// Gets the action name.
        /// </summary>
        public string ActionName => _actionName;

        /// <summary>
        /// Gets whether the action is currently running.
        /// </summary>
        public bool IsRunning => _currentResult == ActionResult.Running;

        /// <summary>
        /// Starts the test action execution.
        /// </summary>
        public void StartAction()
        {
            if (_currentResult == ActionResult.Running)
            {
                UnityEngine.Debug.LogWarning($"[TestAction] {_actionName} is already running.");
                return;
            }

            _elapsedTime = 0f;
            SetResult(ActionResult.Running);
            UnityEngine.Debug.Log($"[TestAction] {_actionName} started.");
        }

        /// <summary>
        /// Resets the action to its initial state.
        /// </summary>
        public void ResetAction()
        {
            _elapsedTime = 0f;
            SetResult(ActionResult.NotStarted);
        }

        /// <summary>
        /// Forces the action to complete with a specific result.
        /// </summary>
        public void ForceComplete(ActionResult result)
        {
            if (result == ActionResult.Running || result == ActionResult.NotStarted)
            {
                UnityEngine.Debug.LogWarning($"[TestAction] Cannot force complete with {result}.");
                return;
            }

            CompleteAction(result);
        }

        private void Update()
        {
            if (_currentResult != ActionResult.Running) return;

            _elapsedTime += Time.deltaTime;

            if (_elapsedTime >= _duration)
            {
                CompleteAction(_shouldSucceed ? ActionResult.Success : ActionResult.Failure);
            }
        }

        private void SetResult(ActionResult result)
        {
            if (_currentResult != result)
            {
                _currentResult = result;
                OnStateChanged?.Invoke(result);
            }
        }

        private void CompleteAction(ActionResult result)
        {
            SetResult(result);
            OnActionComplete?.Invoke(result);
            UnityEngine.Debug.Log($"[TestAction] {_actionName} completed with result: {result}");
        }

        /// <summary>
        /// Creates a test action configuration.
        /// </summary>
        public void Configure(string name, float duration, bool shouldSucceed)
        {
            _actionName = name;
            _duration = duration;
            _shouldSucceed = shouldSucceed;
            ResetAction();
        }
    }
}
// Pseudocode generated by codewrx.ai