using UnityEngine;
using UnityEngine.UI;
using System.Collections;

namespace Lineage.Tests
{
    /// <summary>
    /// Test component for button animation effects.
    /// Verifies hover, click, and state transition animations.
    /// </summary>
    public class ButtonAnimationTester : MonoBehaviour
    {
        [Header("Test Configuration")]
        [SerializeField] private Button _targetButton;
        [SerializeField] private float _testInterval = 1f;
        [SerializeField] private bool _runOnStart = false;

        [Header("Animation Settings")]
        [SerializeField] private Vector3 _hoverScale = new Vector3(1.1f, 1.1f, 1f);
        [SerializeField] private Vector3 _clickScale = new Vector3(0.95f, 0.95f, 1f);
        [SerializeField] private float _animationDuration = 0.2f;

        private Vector3 _originalScale;
        private Coroutine _currentAnimation;

        private void Awake()
        {
            if (_targetButton != null)
            {
                _originalScale = _targetButton.transform.localScale;
            }
        }

        private void Start()
        {
            if (_runOnStart)
            {
                StartCoroutine(RunAllTests());
            }
        }

        /// <summary>
        /// Runs all animation tests sequentially.
        /// </summary>
        public IEnumerator RunAllTests()
        {
            UnityEngine.Debug.Log("[ButtonAnimationTester] Starting animation tests...");

            yield return TestHoverAnimation();
            yield return new WaitForSeconds(_testInterval);

            yield return TestClickAnimation();
            yield return new WaitForSeconds(_testInterval);

            yield return TestStateTransition();

            UnityEngine.Debug.Log("[ButtonAnimationTester] All animation tests completed.");
        }

        /// <summary>
        /// Tests the hover animation effect.
        /// </summary>
        public IEnumerator TestHoverAnimation()
        {
            if (_targetButton == null)
            {
                UnityEngine.Debug.LogWarning("[ButtonAnimationTester] No target button assigned.");
                yield break;
            }

            UnityEngine.Debug.Log("[ButtonAnimationTester] Testing hover animation...");
            yield return AnimateScale(_targetButton.transform, _hoverScale, _animationDuration);
            yield return new WaitForSeconds(0.5f);
            yield return AnimateScale(_targetButton.transform, _originalScale, _animationDuration);
        }

        /// <summary>
        /// Tests the click animation effect.
        /// </summary>
        public IEnumerator TestClickAnimation()
        {
            if (_targetButton == null) yield break;

            UnityEngine.Debug.Log("[ButtonAnimationTester] Testing click animation...");
            yield return AnimateScale(_targetButton.transform, _clickScale, _animationDuration * 0.5f);
            yield return AnimateScale(_targetButton.transform, _originalScale, _animationDuration * 0.5f);
        }

        /// <summary>
        /// Tests state transition animations.
        /// </summary>
        public IEnumerator TestStateTransition()
        {
            if (_targetButton == null) yield break;

            UnityEngine.Debug.Log("[ButtonAnimationTester] Testing state transitions...");
            
            _targetButton.interactable = false;
            yield return new WaitForSeconds(0.3f);
            
            _targetButton.interactable = true;
            yield return new WaitForSeconds(0.3f);
        }

        private IEnumerator AnimateScale(Transform target, Vector3 targetScale, float duration)
        {
            Vector3 startScale = target.localScale;
            float elapsed = 0f;

            while (elapsed < duration)
            {
                elapsed += Time.deltaTime;
                float t = Mathf.SmoothStep(0f, 1f, elapsed / duration);
                target.localScale = Vector3.Lerp(startScale, targetScale, t);
                yield return null;
            }

            target.localScale = targetScale;
        }

        /// <summary>
        /// Sets the target button for testing.
        /// </summary>
        public void SetTargetButton(Button button)
        {
            _targetButton = button;
            if (_targetButton != null)
            {
                _originalScale = _targetButton.transform.localScale;
            }
        }
    }
}
// Pseudocode generated by codewrx.ai